package pe.edu.upc.viora.features.climate.domain.entity

import java.time.Instant
import pe.edu.upc.viora.features.plotmanagement.domain.valueobject.PlotId

/**
 * Complete 7-day meteorological forecast bundle for an olive plot.
 *
 * @property plotId Identifier of the olive plot.
 * @property dailyForecasts List of daily forecasts ordered chronologically (typically 7 days).
 * @property generatedAt Timestamp when this forecast dataset was generated by the backend.
 */
data class WeatherForecast(
    val plotId: PlotId,
    val dailyForecasts: List<DayForecast>,
    val generatedAt: Instant,
)
